# Generated by Django 3.2.8 on 2021-10-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main_app.cars')),
            ],
        ),
    ]
