# Generated by Django 3.2.8 on 2021-10-08 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='img',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
